 python src/certHML.py contracts/bank/bank.sol Additivity 2 30
 python src/certHML.py contracts/bank/bank.sol Reversibility_deposit 2 30
 python src/certHML.py contracts/bank/bank.sol Liquidity 2 30
 python src/certHML.py contracts/bank/bank.sol No_frontrun_deposit 2 30
 python src/certHML.py contracts/bank/bank_v2.sol Additivity 2 30
 python src/certHML.py contracts/bank/bank_v2.sol Reversibility_deposit 2 30
 python src/certHML.py contracts/bank/bank_v2.sol Liquidity 2 30
 python src/certHML.py contracts/bank/bank_v2.sol No_frontrun_deposit 2 30
 python src/certHML.py contracts/bank/bank_v3.sol Additivity 2 30
 python src/certHML.py contracts/bank/bank_v3.sol Reversibility_deposit 2 30
 python src/certHML.py contracts/bank/bank_v3.sol Liquidity 2 30
 python src/certHML.py contracts/bank/bank_v3.sol No_frontrun_deposit 2 30
 python src/certHML.py contracts/bank/bank_v5.sol Additivity 2 30
 python src/certHML.py contracts/bank/bank_v5.sol Reversibility_deposit 2 30
 python src/certHML.py contracts/bank/bank_v5.sol Liquidity 2 30
 python src/certHML.py contracts/bank/bank_v5.sol No_frontrun_deposit 2 30
 python src/certHML.py contracts/vault/vault.sol Two_steps_drainability 2 30
 python src/certHML.py contracts/vault/vault.sol Two_steps_drainability_non_inflation 2 30
 python src/certHML.py contracts/vault/vault_v2.sol Two_steps_drainability 2 30
 python src/certHML.py contracts/vault/vault_v2.sol Two_steps_drainability_non_inflation 2 30
 python src/certHML.py contracts/vault/vault_v3.sol Two_steps_drainability 2 30
 python src/certHML.py contracts/vault/vault_v3.sol Two_steps_drainability_non_inflation 2 30
 python src/certHML.py contracts/price-bet/price-bet.sol Running_example1 2 30
 python src/certHML.py contracts/price-bet/price-bet.sol Running_example2 2 30
 python src/certHML.py contracts/price-bet/price-bet.sol Running_example3_Frontrun_simple 2 30
 python src/certHML.py contracts/price-bet/price-bet_v2.sol Running_example1 2 30
 python src/certHML.py contracts/price-bet/price-bet_v2.sol Running_example2 2 30
 python src/certHML.py contracts/price-bet/price-bet_v2.sol Running_example3_Frontrun_simple 2 30    
 python src/certHML.py contracts/price-bet/price-bet_v3.sol Running_example1 2 30
 python src/certHML.py contracts/price-bet/price-bet_v3.sol Running_example2 2 30
 python src/certHML.py contracts/price-bet/price-bet_v3.sol Running_example3_Frontrun_simple 2 30
